Create Database Consultorio;

Use Consultorio;

CREATE TABLE Consulta(
    CURP VARCHAR(16),
    Nombre VARCHAR(20),
    Apellidos VARCHAR(40),
    Sexo VARCHAR(10),
    Edad INT,
    Peso FLOAT,
    Direccion VARCHAR(60),
    Email VARCHAR(50),
    Telefono INT,
    Fecha date,
    CEDULA INT,
    Nombre_Medico VARCHAR(20),
    Apellidos_Medico VARCHAR(40),
    CEDULA_ESP INT,
    Especialidad VARCHAR(20),
    Direccion_Medico VARCHAR(60),
    Telefono_Medico INT,
    Email_Medico VARCHAR(50),
    RFC VARCHAR(12),
    Razon_Social VARCHAR(30),
    Tipo_Persona VARCHAR(20),
    Direccion_Fiscal VARCHAR(20),
    Calle VARCHAR(20),
    Num_Exterior INT,
    Num_Interior INT,
    Comunidad VARCHAR(20),
    Estado VARCHAR(20),
    Codigo_Postal INT,
    Pais VARCHAR(20),
    Id_Servicio INT,
    Cirujia VARCHAR(2),
    Curacion VARCHAR(2),
    Tratamiento VARCHAR(2),
    Procedimiento VARCHAR(2),
    Costo_Servicio FLOAT,
    Dias_Uso INT, 
    Costo_Habitacion FLOAT, 
    Folio_Pago INT PRIMARY KEY Auto_Increment);